# CI de Nivel 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execuçao Manual'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

# trabalhos ou tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build (steps)
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalaçao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalaçao do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalaçao das dependencias
      - name: Instalando dependencias
        run: yarn

      # instalaçao do Playwrigth
      - name: Instalando Playwrigth
        run: yarn playwrigth install

      # instalaçao dos testes e2e
      - name: Executando Testes E2E
        run: yarn runb e2e