# CI de Nivel 03 - Disparo apos a conclusao de um pipeline

# nome do nosso 'pipeline'
name: 'Execuçao por Deploy'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch
# gatilho de exec agendada = schedule
# gatilho de exec apos o deploy  - a partir de outro pipeline = workflow_run

on:
  workflow_run:
    workflows: ['Execuçao Manual']
    types:
      - completed

# trabalhos ou tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # condicional - if
    # '${expressao}' - expressao do github actions
    # == comparacao de igualdade

    if: ${{ github.event.workflow_run.conclusion == 'success' }}


    # passos do script de build (steps)
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalaçao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalaçao do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalaçao das dependencias
      - name: Instalando dependencias
        run: yarn

      # instalaçao do Playwrigth
      - name: Instalando playwright
        run: yarn playwright install

      # instalaçao dos testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report  